[package]
name = "system-entity"
version.workspace = true
edition.workspace = true

[features]
default = ["sea-orm", "sea-orm-ext", "sea-query"]
sea-orm = ["dep:sea-orm"]
sea-orm-ext = ["dep:sea-orm-ext", "sea-orm", "sea-query"]

[dependencies]
common = { workspace = true }
sea-orm = { workspace = true, optional = true }
sea-orm-ext = { workspace = true, optional = true }
sea-query = { workspace = true, optional = true }
async-trait = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }