[package]
name = "system-application"
version.workspace = true
edition.workspace = true

[features]
default = ["sea-orm", "sea-orm-ext", "sea-query", "sa-token", "summer", "summer-redis", "monitor", "http-client", "compression"]
sea-orm = ["dep:sea-orm", "common/sea-orm"]
sea-orm-ext = ["dep:sea-orm-ext", "common/sea-orm-ext", "system-entity/sea-orm-ext"]
sa-token = ["dep:summer-sa-token", "dep:sa-token-core", "dep:sa-token-adapter", "common/sa-token"]
summer = ["dep:summer"]
summer-redis = ["dep:summer-redis"]
monitor = ["dep:sysinfo", "dep:num_cpus"]
http-client = ["dep:reqwest"]
compression = ["dep:zip"]

[dependencies]
system-entity = { workspace = true }
common = { workspace = true }
sea-orm = { workspace = true, optional = true }
sea-orm-ext = { workspace = true, optional = true }
sea-query = { workspace = true, optional = true }
summer = { workspace = true, optional = true }
summer-sa-token = { workspace = true, optional = true, features = ["with-summer-redis"] }
summer-redis = { workspace = true, optional = true }
sa-token-core = { workspace = true, optional = true }
sa-token-adapter = { workspace = true, optional = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zip = { workspace = true, optional = true }
sysinfo = { workspace = true, optional = true }
num_cpus = { workspace = true, optional = true }
tokio = { workspace = true, features = ["time"] }
log = { workspace = true }
reqwest = { workspace = true, optional = true }
