[package]
name = "common"
version.workspace = true
edition.workspace = true

[features]
default = ["sa-token", "sea-orm", "sea-orm-ext", "sea-query"]
sa-token = ["dep:summer-sa-token", "dep:sa-token-core"]
sea-orm = ["dep:sea-orm"]
sea-orm-ext = ["dep:sea-orm-ext", "sea-orm"]

[dependencies]
sea-orm = { workspace = true, optional = true }
sea-orm-ext = { workspace = true, optional = true }
sea-query = { workspace = true, optional = true }
summer-sa-token = { workspace = true, optional = true }
sa-token-core = { workspace = true, optional = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
bcrypt = "0.15"
