[package]
name = "system-infrastructure"
version.workspace = true
edition.workspace = true

[features]
default = ["sea-orm", "sea-orm-ext"]
sea-orm = ["dep:sea-orm", "common/sea-orm"]
sea-orm-ext = ["dep:sea-orm-ext", "common/sea-orm-ext"]

[dependencies]
system-entity = { workspace = true }
system-domain = { workspace = true }
common = { workspace = true }
sea-orm = { workspace = true, optional = true }
sea-orm-ext = { workspace = true, optional = true }
async-trait = { workspace = true }
chrono = { workspace = true }
summer = { workspace = true }
serde = { workspace = true }
rust-s3 = { workspace = true }
tokio = { workspace = true, features = ["fs"] }