[package]
name = "system-domain"
version.workspace = true
edition.workspace = true

[features]
default = ["sea-orm"]
sea-orm = ["dep:sea-orm"]

[dependencies]
system-entity = { workspace = true }
common = { workspace = true }
sea-orm = { workspace = true, optional = true }
async-trait = { workspace = true }
